// SPDX-FileCopyrightText: 2025 NOI Techpark <digital@noi.bz.it>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ViewLayout } from "./utils/breakpoints";
import { EmissionData } from "./data/emissions/EmissionData";
import { IconName } from "./blocks/icon/icon.component";
import { Map } from "leaflet";
export { ViewLayout } from "./utils/breakpoints";
export { EmissionData } from "./data/emissions/EmissionData";
export { IconName } from "./blocks/icon/icon.component";
export { Map } from "leaflet";
export namespace Components {
    /**
     * Road air quality component
     */
    interface NoiA22EmissionIndex {
        /**
          * Language
         */
        "language": string;
        /**
          * Layout appearance
         */
        "layout": ViewLayout;
        /**
          * Hides legend threshold values
         */
        "legendHideThreshold": boolean;
        /**
          * Reload camera data
         */
        "refreshData": () => Promise<void>;
    }
    /**
     * (INTERNAL) Backdrop component.
     */
    interface NoiButton {
        /**
          * button 'disabled' property
          * @default false
         */
        "disabled": boolean;
        /**
          * icon-only buttons has circle shape. The size of the button can be changed with "font-size" style
          * @default false
         */
        "iconOnly": boolean;
    }
    /**
     * (INTERNAL)
     */
    interface NoiEmissionDataList {
        "idSelected": string;
        "stationArr": EmissionData[] | null;
    }
    /**
     * (INTERNAL) render an icon.
     * Icons are embedded inside the component (so far).
     * Icon size can be changed by 'font-size' style
     */
    interface NoiIcon {
        /**
          * icon name
         */
        "name": IconName | string;
    }
    /**
     * (INTERNAL) render an input with prefix and clear button
     * Prefix are hardcoded to 'search' icon for now.
     */
    interface NoiInput {
        /**
          * Input placeholder
         */
        "placeholder": string;
    }
    /**
     * (INTERNAL) render leaflet map
     */
    interface NoiMap {
    }
}
export interface NoiButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiButtonElement;
}
export interface NoiEmissionDataListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiEmissionDataListElement;
}
export interface NoiInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiInputElement;
}
export interface NoiMapCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiMapElement;
}
declare global {
    /**
     * Road air quality component
     */
    interface HTMLNoiA22EmissionIndexElement extends Components.NoiA22EmissionIndex, HTMLStencilElement {
    }
    var HTMLNoiA22EmissionIndexElement: {
        prototype: HTMLNoiA22EmissionIndexElement;
        new (): HTMLNoiA22EmissionIndexElement;
    };
    interface HTMLNoiButtonElementEventMap {
        "btnClick": MouseEvent;
    }
    /**
     * (INTERNAL) Backdrop component.
     */
    interface HTMLNoiButtonElement extends Components.NoiButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiButtonElementEventMap>(type: K, listener: (this: HTMLNoiButtonElement, ev: NoiButtonCustomEvent<HTMLNoiButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiButtonElementEventMap>(type: K, listener: (this: HTMLNoiButtonElement, ev: NoiButtonCustomEvent<HTMLNoiButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiButtonElement: {
        prototype: HTMLNoiButtonElement;
        new (): HTMLNoiButtonElement;
    };
    interface HTMLNoiEmissionDataListElementEventMap {
        "itemClick": EmissionData;
    }
    /**
     * (INTERNAL)
     */
    interface HTMLNoiEmissionDataListElement extends Components.NoiEmissionDataList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiEmissionDataListElementEventMap>(type: K, listener: (this: HTMLNoiEmissionDataListElement, ev: NoiEmissionDataListCustomEvent<HTMLNoiEmissionDataListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiEmissionDataListElementEventMap>(type: K, listener: (this: HTMLNoiEmissionDataListElement, ev: NoiEmissionDataListCustomEvent<HTMLNoiEmissionDataListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiEmissionDataListElement: {
        prototype: HTMLNoiEmissionDataListElement;
        new (): HTMLNoiEmissionDataListElement;
    };
    /**
     * (INTERNAL) render an icon.
     * Icons are embedded inside the component (so far).
     * Icon size can be changed by 'font-size' style
     */
    interface HTMLNoiIconElement extends Components.NoiIcon, HTMLStencilElement {
    }
    var HTMLNoiIconElement: {
        prototype: HTMLNoiIconElement;
        new (): HTMLNoiIconElement;
    };
    interface HTMLNoiInputElementEventMap {
        "valueChange": string;
    }
    /**
     * (INTERNAL) render an input with prefix and clear button
     * Prefix are hardcoded to 'search' icon for now.
     */
    interface HTMLNoiInputElement extends Components.NoiInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiInputElementEventMap>(type: K, listener: (this: HTMLNoiInputElement, ev: NoiInputCustomEvent<HTMLNoiInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiInputElementEventMap>(type: K, listener: (this: HTMLNoiInputElement, ev: NoiInputCustomEvent<HTMLNoiInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiInputElement: {
        prototype: HTMLNoiInputElement;
        new (): HTMLNoiInputElement;
    };
    interface HTMLNoiMapElementEventMap {
        "mapReady": Map;
    }
    /**
     * (INTERNAL) render leaflet map
     */
    interface HTMLNoiMapElement extends Components.NoiMap, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiMapElementEventMap>(type: K, listener: (this: HTMLNoiMapElement, ev: NoiMapCustomEvent<HTMLNoiMapElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiMapElementEventMap>(type: K, listener: (this: HTMLNoiMapElement, ev: NoiMapCustomEvent<HTMLNoiMapElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiMapElement: {
        prototype: HTMLNoiMapElement;
        new (): HTMLNoiMapElement;
    };
    interface HTMLElementTagNameMap {
        "noi-a22-emission-index": HTMLNoiA22EmissionIndexElement;
        "noi-button": HTMLNoiButtonElement;
        "noi-emission-data-list": HTMLNoiEmissionDataListElement;
        "noi-icon": HTMLNoiIconElement;
        "noi-input": HTMLNoiInputElement;
        "noi-map": HTMLNoiMapElement;
    }
}
declare namespace LocalJSX {
    /**
     * Road air quality component
     */
    interface NoiA22EmissionIndex {
        /**
          * Language
         */
        "language"?: string;
        /**
          * Layout appearance
         */
        "layout"?: ViewLayout;
        /**
          * Hides legend threshold values
         */
        "legendHideThreshold"?: boolean;
    }
    /**
     * (INTERNAL) Backdrop component.
     */
    interface NoiButton {
        /**
          * button 'disabled' property
          * @default false
         */
        "disabled"?: boolean;
        /**
          * icon-only buttons has circle shape. The size of the button can be changed with "font-size" style
          * @default false
         */
        "iconOnly"?: boolean;
        /**
          * Emitted when user clicks on the button
         */
        "onBtnClick"?: (event: NoiButtonCustomEvent<MouseEvent>) => void;
    }
    /**
     * (INTERNAL)
     */
    interface NoiEmissionDataList {
        "idSelected"?: string;
        "onItemClick"?: (event: NoiEmissionDataListCustomEvent<EmissionData>) => void;
        "stationArr"?: EmissionData[] | null;
    }
    /**
     * (INTERNAL) render an icon.
     * Icons are embedded inside the component (so far).
     * Icon size can be changed by 'font-size' style
     */
    interface NoiIcon {
        /**
          * icon name
         */
        "name"?: IconName | string;
    }
    /**
     * (INTERNAL) render an input with prefix and clear button
     * Prefix are hardcoded to 'search' icon for now.
     */
    interface NoiInput {
        /**
          * Emitted when value is changed
         */
        "onValueChange"?: (event: NoiInputCustomEvent<string>) => void;
        /**
          * Input placeholder
         */
        "placeholder"?: string;
    }
    /**
     * (INTERNAL) render leaflet map
     */
    interface NoiMap {
        /**
          * Emitted when map is initialized and ready to draw on it
         */
        "onMapReady"?: (event: NoiMapCustomEvent<Map>) => void;
    }
    interface IntrinsicElements {
        "noi-a22-emission-index": NoiA22EmissionIndex;
        "noi-button": NoiButton;
        "noi-emission-data-list": NoiEmissionDataList;
        "noi-icon": NoiIcon;
        "noi-input": NoiInput;
        "noi-map": NoiMap;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Road air quality component
             */
            "noi-a22-emission-index": LocalJSX.NoiA22EmissionIndex & JSXBase.HTMLAttributes<HTMLNoiA22EmissionIndexElement>;
            /**
             * (INTERNAL) Backdrop component.
             */
            "noi-button": LocalJSX.NoiButton & JSXBase.HTMLAttributes<HTMLNoiButtonElement>;
            /**
             * (INTERNAL)
             */
            "noi-emission-data-list": LocalJSX.NoiEmissionDataList & JSXBase.HTMLAttributes<HTMLNoiEmissionDataListElement>;
            /**
             * (INTERNAL) render an icon.
             * Icons are embedded inside the component (so far).
             * Icon size can be changed by 'font-size' style
             */
            "noi-icon": LocalJSX.NoiIcon & JSXBase.HTMLAttributes<HTMLNoiIconElement>;
            /**
             * (INTERNAL) render an input with prefix and clear button
             * Prefix are hardcoded to 'search' icon for now.
             */
            "noi-input": LocalJSX.NoiInput & JSXBase.HTMLAttributes<HTMLNoiInputElement>;
            /**
             * (INTERNAL) render leaflet map
             */
            "noi-map": LocalJSX.NoiMap & JSXBase.HTMLAttributes<HTMLNoiMapElement>;
        }
    }
}
